//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDM_MENU                        101
#define IDM_NEW_PROJECT                 102
#define IDM_LOAD_PROJECT                103
#define IDM_SAVE_PROJECT                104
#define IDM_SAVEIMAGE                   105
#define IDM_EXIT                        106
#define IDM_CUT                         107
#define IDM_COPY                        108
#define IDM_PASTE                       109
#define IDM_GRID                        110
#define IDM_DRAWLINE                    111
#define IDM_DRAWCIRCLE                  112
#define IDM_DRAWTRIANGLE                113
#define IDM_FILLCOLOR                   114
#define IDM_CLEARALL                    115
#define IDM_LINECOLLISION               116
#define IDM_CIRCLECOLLISION             117
#define IDM_FLIPNORMAL                  118
#define IDD_DIALOG1                     125
#define IDD_LISTDIALOG                  125
#define ID_Menu                         126
#define IDM_GENERATE                    127
#define IDM_CLEANCODE                   128
#define IDM_ABOUT                       129
#define IDM_NEWCHARACTE                 130
#define ID_CHARACTERDESIGN_SAVECHARACTER 131
#define IDM_GAMESETTINGS                132
#define IDM_CAM_VIEW_SETTINGS           133
#define IDM_CHARACTERPROPERTIES         134
#define IDM_TWOWAY                      135
#define IDD_GAMESETTINGS                136
#define IDD_CAMSETTINGS                 137
#define IDD_CAM_AND_VIEW_SETTINGS       137
#define IDD_CHARACTER                   138
#define IDD_DIALOG_CHAR_PROPERTIES      138
#define IDD_MOVEMENT                    139
#define IDM_MOVEMENT                    140
#define IDR_MOVEMENT_MENU               141
#define IDM_MOVEMENT_FREE               142
#define IDM_MOVEMENT_LINE               143
#define IDM_MOVEMENT_CIRCLE             144
#define IDM_MOVEMENT_ELLIPSE            145
#define IDM_MOVEMENT_INITIAL            146
#define IDM_MOVEMENT_CLOSED             147
#define IDD_DIALOG_CAMSETTINGS          148
#define IDD_DIALOG2                     149
#define IDD_DIALOG_VIEWSETTINGS         149
#define IDD_DIALOG_CHAR_DESIGN          150
#define IDC_DROPPER                     152
#define IDD_DIALOG_CHAR_SDRECT          159
#define IDR_TOOLBAR1                    160
#define IDI_ICON                        300
#define IDC_LIST1                       1001
#define IDM_REMOVE                      1002
#define IDM_SELECT                      1003
#define IDM_DRAW                        1004
#define IDM_WINDOW_WIDTH                1006
#define IDD_WINDOW_WIDTH                1006
#define IDM_WINDOW_HEIGHT               1007
#define IDD_WINDOW_HEIGHT               1007
#define IDM_WINDOW_STYLE                1008
#define IDD_WINDOW_STYLE                1008
#define IDM_FRAMERATE                   1010
#define IDD_FRAMERATE                   1010
#define IDD_MAIN_CAMCENTERX             1011
#define IDD_MAIN_CAMCENTERY             1012
#define IDD_CHARACTER_POSX              1012
#define IDD_MAIN_CAMWIDTH               1013
#define IDD_CHARACTER_POSY              1013
#define IDD_MAIN_CAMHEIGHT              1014
#define IDD_CHARACTER_SCALE             1014
#define IDD_MAIN_VIEWCENTERX            1015
#define IDD_CHARACTER_ANGLE             1015
#define IDD_MAIN_VIEWCENTERY            1016
#define IDD_CHARACTER_SPEED             1016
#define IDD_MAIN_VIEWWIDTH              1017
#define IDD_CHARACTER_DIRECTIONX        1017
#define IDD_MAIN_VIEWHEIGHT             1018
#define IDD_CHARACTER_DIRECTIONY        1018
#define IDD_CHARACTER_ANGULARSPEED      1019
#define IDD_CHARACTER_RED               1020
#define IDD_CHARACTER_GREEN             1021
#define IDC_BUTTON_MAIN_CAMERASETTINGS  1021
#define IDD_CHARACTER_BLUE              1022
#define IDC_BUTTON_MAIN_VIEWPORTSETTINGS 1022
#define IDC_BUTTON_RADAR_CAMERASETTINGS 1023
#define IDC_BUTTON_RADAR_VIEWPORTSETTINGS 1024
#define IDC_EDIT_CAM_CENTER_X           1025
#define IDC_EDIT_CAM_CENTER_Y           1026
#define IDD_RADAR_CAMCENTERX            1027
#define IDC_EDIT_CAM_WIDTH              1027
#define IDD_RADAR_CAMCENTERY            1028
#define IDC_EDIT_CAM_HEIGHT             1028
#define IDD_RADAR_CAMWIDTH              1029
#define IDC_EDIT_CAM_ANGLE              1029
#define IDD_RADAR_CAMHEIGHT             1030
#define IDD_RADAR_VIEWCENTERX           1031
#define IDC_EDIT_CAM_SCALE              1031
#define IDD_RADAR_VIEWCENTERY           1032
#define IDD_RADAR_VIEWWIDTH             1033
#define IDC_EDIT_SBB_LEFT               1033
#define IDD_RADAR_VIEWHEIGHT            1034
#define IDC_EDIT_SBB_RIGHT              1035
#define IDC_EDIT_SBB_TOP                1036
#define IDC_EDIT_SBB_BOTTOM             1037
#define IDC_CHECK2                      1038
#define IDC_CHECK                       1038
#define IDC_CHECK_SBB                   1038
#define IDC_CHECK_DRAW_TRIANGLE_FILLED  1038
#define IDC_EDIT_VIEW_CENTER_X          1039
#define IDC_EDIT_VIEW_CENTER_Y          1040
#define IDC_EDIT_VIEW_WIDTH             1041
#define IDC_EDIT_VIEW_HEIGHT            1042
#define IDC_RADIO_DRAW_LINE             1043
#define IDC_RADIO_DRAW_CIRCLE           1044
#define IDC_RADIO_DRAW_TRIANGLE         1045
#define IDC_CHECK_DRAW_CIRCLE_FILLED    1046
#define IDC_CHECK_DRAW_PRIMITIVE_FILLED 1046
#define IDC_BUTTON_CHAR_ADD             1047
#define IDC_BUTTON_CHAR_PROPERTIES      1048
#define IDC_BUTTON_CHAR_COLLISION       1049
#define IDC_LIST_CHAR                   1050
#define IDC_CHECK_COLLISION_FLIPNORMAL  1051
#define IDC_CHECK_COLLISION_TWOWAYCHECK 1052
#define IDC_BUTTON_CHAR_DRAW            1053
#define IDC_EDIT_CHAR_RED               1054
#define IDC_EDIT_CHAR_GREEN             1055
#define IDC_EDIT_CHAR_BLUE              1056
#define IDC_STATIC_CHAR_RED             1057
#define IDC_STATIC_CHAR_GREEN           1058
#define IDC_STATIC_CHAR_BLUE            1059
#define IDC_STATIC_COMBINE_1            1060
#define IDC_STATIC_COMBINE_2            1061
#define IDC_STATIC_COMBINE_3            1062
#define IDC_STATIC_COMBINE_4            1063
#define IDC_STATIC_COMBINE_5            1064
#define IDC_RADIO_CHAR_COLLISION_LINE   1065
#define IDC_RADIO_CHAR_COLLISION_CIRCLE 1066
#define IDC_EDIT_CHAR_NAME              1067
#define IDC_BUTTON1                     1068
#define IDC_BUTTON_CHAR_SAVECHANGES     1068
#define IDC_BUTTON_CHAR_NEWCHAR         1069
#define IDC_BUTTON_CHAR_REMOVECHAR      1070
#define IDC_STATIC_CHAR_COLORSELECTION  1071
#define IDC_STATIC_CHAR_COLORPREVIEW    1072
#define IDC_BUTTON2                     1073
#define IDC_BUTTON_CHAR_PICKCOLOR       1073
#define IDC_CHAR_MODE                   1074
#define IDC_BUTTON_CHAR_MODE            1074
#define IDC_BUTTON_CHAR_SDRECT          1075
#define IDC_EDIT_SWIDTH                 1076
#define IDC_EDIT_SHEIGHT                1077
#define IDC_EDIT_DWIDTH                 1078
#define IDC_EDIT_DHEIGHT                1079
#define IDC_CHECK1                      1080
#define IDC_CHECK_CHAR_SDRect_SHOW      1080
#define IDC_BUTTON3                     1082
#define IDC_BUTTON_CHAR_REMOVE          1082
#define IDM_CHAR_SHOWDIALOG             1132
#define IDC_STYLE_OVERLAPPED            1083
#define IDC_STYLE_POPUP                 1084
#define IDC_STYLE_SYSMENU               1085
#define IDC_STYLE_SYSMENU2              1086
#define IDC_STYLE_VISIBLE               1086
#define IDC_STYLE_MINIMIZE              1087
#define IDC_STYLE_MAXIMIZE              1088
#define IDC_STYLE_CAPTION               1089
#define IDC_STYLE_BORDER                1090
#define ID_TOOLGAMESETTINGS             40001
#define ID_TOOLVIEWCAM                  40002
#define ID_TOOLCHARACTER                40003
#define ID_TOOLBUILD                    40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
